import {
  Activity,
  Apple,
  Book,
  Brain,
  Camera,
  CheckSquare,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  Footprints,
  Gamepad2,
  GraduationCap,
  Guitar,
  Hammer,
  Heart,
  Home,
  Lightbulb,
  MessageCircle,
  Mic,
  Monitor,
  Mountain,
  Music,
  Palette,
  PenTool,
  Pill,
  Plane,
  Puzzle,
  Search,
  Smartphone,
  Stethoscope,
  Sun,
  Target,
  TreesIcon as Tree,
  Users,
  Utensils,
  Bike,
  Car,
  Headphones,
  Leaf,
  Moon,
  Scissors,
  ShoppingCart,
  Smile,
  Star,
  Zap,
  Waves,
  Wind,
  Wrench,
  SpaceIcon as Yoga,
  Fish,
  Flower,
  Globe,
  Compass,
  Video,
  Radio,
  Tv,
  Dice1,
  Trophy,
  Medal,
  Flag,
  Rocket,
  Sparkles,
  type LucideIcon,
  Plus,
  CircleCheckBig,
  CircleFadingPlus,
  ChartNoAxesCombined,
} from "lucide-react";
export const daysOfWeek = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const squareSize = 10;
export const borderRadius = 2;
export const gridGap = 3;

export const features = [
  {
    name: "Visual Progress",
    desc: "See your habits build up day by day with our unique grid visualization, making progress satisfying and clear.",
    icon: CircleCheckBig,
  },
  {
    name: "Simple Setup",
    desc: "Add new habits in seconds with an intuitive interface, allowing you to focus on building, not configuring.",
    icon: CircleFadingPlus,
  },
  {
    name: "Stay Consistent",
    desc: "Mark habits complete with a tap and see your consistency grow, building powerful momentum.",
    icon: ChartNoAxesCombined,
  },
];

export const colorMap: Record<
  string,
  {
    light: string;
    normal: string;
    dark: string;
  }
> = {
  red: {
    light: "bg-red-400/10",
    normal: "bg-red-400/80",
    dark: "bg-red-400/15",
  },
  orange: {
    light: "bg-orange-400/10",
    normal: "bg-orange-400/80",
    dark: "bg-orange-400/15",
  },
  amber: {
    light: "bg-amber-400/10",
    normal: "bg-amber-400/80",
    dark: "bg-amber-400/15",
  },
  yellow: {
    light: "bg-yellow-400/10",
    normal: "bg-yellow-400/80",
    dark: "bg-yellow-400/15",
  },
  lime: {
    light: "bg-lime-400/10",
    normal: "bg-lime-400/80",
    dark: "bg-lime-400/15",
  },
  green: {
    light: "bg-green-400/10",
    normal: "bg-green-400/80",
    dark: "bg-green-400/15",
  },
  emerald: {
    light: "bg-emerald-400/10",
    normal: "bg-emerald-400/80",
    dark: "bg-emerald-400/15",
  },
  teal: {
    light: "bg-teal-400/10",
    normal: "bg-teal-400/80",
    dark: "bg-teal-400/15",
  },
  cyan: {
    light: "bg-cyan-400/10",
    normal: "bg-cyan-400/80",
    dark: "bg-cyan-400/15",
  },
  sky: {
    light: "bg-sky-400/10",
    normal: "bg-sky-400/80",
    dark: "bg-sky-400/15",
  },
  blue: {
    light: "bg-blue-400/10",
    normal: "bg-blue-400/80",
    dark: "bg-blue-400/15",
  },
  indigo: {
    light: "bg-indigo-400/10",
    normal: "bg-indigo-400/80",
    dark: "bg-indigo-400/15",
  },
  violet: {
    light: "bg-violet-400/10",
    normal: "bg-violet-400/80",
    dark: "bg-violet-400/15",
  },
  purple: {
    light: "bg-purple-400/10",
    normal: "bg-purple-400/80",
    dark: "bg-purple-400/15",
  },
  fuchsia: {
    light: "bg-fuchsia-400/10",
    normal: "bg-fuchsia-400/80",
    dark: "bg-fuchsia-400/15",
  },
  pink: {
    light: "bg-pink-400/10",
    normal: "bg-pink-400/80",
    dark: "bg-pink-400/15",
  },
  rose: {
    light: "bg-rose-400/10",
    normal: "bg-rose-400/80",
    dark: "bg-rose-400/15",
  },
  slate: {
    light: "bg-slate-400/10",
    normal: "bg-slate-400/80",
    dark: "bg-slate-400/15",
  },
  gray: {
    light: "bg-gray-400/10",
    normal: "bg-gray-400/80",
    dark: "bg-gray-400/15",
  },
  zinc: {
    light: "bg-zinc-400/10",
    normal: "bg-zinc-400/80",
    dark: "bg-zinc-400/15",
  },
  neutral: {
    light: "bg-neutral-400/10",
    normal: "bg-neutral-400/80",
    dark: "bg-neutral-400/15",
  },
  stone: {
    light: "bg-stone-400/10",
    normal: "bg-stone-400/80",
    dark: "bg-stone-400/15",
  },
};

export const iconMap: Record<string, LucideIcon> = {
  Activity,
  Apple,
  Book,
  Brain,
  Camera,
  CheckSquare,
  ChefHat,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  Footprints,
  Gamepad2,
  GraduationCap,
  Guitar,
  Hammer,
  Heart,
  Home,
  Lightbulb,
  MessageCircle,
  Mic,
  Monitor,
  Mountain,
  Music,
  Palette,
  PenTool,
  Pill,
  Plane,
  Puzzle,
  Search,
  Smartphone,
  Stethoscope,
  Sun,
  Target,
  Tree,
  Users,
  Utensils,
  Bike,
  Car,
  Headphones,
  Leaf,
  Moon,
  Scissors,
  ShoppingCart,
  Smile,
  Star,
  Zap,
  Waves,
  Wind,
  Wrench,
  Yoga,
  Fish,
  Flower,
  Globe,
  Compass,
  Video,
  Radio,
  Tv,
  Dice1,
  Trophy,
  Medal,
  Flag,
  Rocket,
  Sparkles,
  Plus,
};
